name: Trigger auto deployment for rollbot-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rollbot-app-AutoDeployTrigger-085a32c9-5d25-41c3-a343-1fedde8e0551.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ROLLBOTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROLLBOTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROLLBOTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: wkfcontainters.azurecr.io
          registryUsername: ${{ secrets.ROLLBOTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROLLBOTAPP_REGISTRY_PASSWORD }}
          containerAppName: rollbot-app
          resourceGroup: Default
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


